# Generated by Django 3.0.5 on 2020-04-02 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale_name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Classified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classified_text', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('time_created', models.TimeField(auto_now_add=True)),
                ('section', models.CharField(max_length=40, verbose_name='section of the postings, eg water, food, shelter')),
                ('narotype', models.CharField(max_length=40, verbose_name='needed, available, resource or organizations')),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifieds.Locale')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifieds.User')),
            ],
        ),
    ]
