# Generated by Django 3.0.5 on 2020-04-05 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0004_remove_classified_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Narotype',
            new_name='Subsection',
        ),
        migrations.RenameField(
            model_name='classified',
            old_name='narotype',
            new_name='subsection',
        ),
        migrations.RenameField(
            model_name='subsection',
            old_name='narotype_name',
            new_name='subsection_name',
        ),
    ]
