# Generated by Django 3.0.5 on 2020-04-08 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0006_auto_20200408_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sublocale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sublocale_name', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(max_length=8)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('region', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('timezone', models.CharField(max_length=200)),
                ('parent_locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifieds.Locale')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
