# Generated by Django 3.0.5 on 2020-04-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0007_auto_20200408_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=200)),
                ('page_text', models.TextField()),
            ],
        ),
    ]
