# Generated by Django 3.0.5 on 2020-04-03 19:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Narotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narotype_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='classified',
            name='classified_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classified',
            name='narotype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifieds.Narotype'),
        ),
        migrations.AlterField(
            model_name='classified',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifieds.Section'),
        ),
    ]
