# Generated by Django 3.0.5 on 2020-04-03 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0003_auto_20200403_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classified',
            name='user',
        ),
    ]
