# Generated by Django 3.0.5 on 2020-04-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0005_auto_20200405_0143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locale',
            old_name='state',
            new_name='region',
        ),
        migrations.AddField(
            model_name='locale',
            name='abbreviation',
            field=models.CharField(default='abb', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locale',
            name='latitude',
            field=models.FloatField(default=333),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locale',
            name='longitude',
            field=models.FloatField(default=333),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locale',
            name='timezone',
            field=models.CharField(default='cst', max_length=200),
            preserve_default=False,
        ),
    ]
