# Generated by Django 3.0.5 on 2020-04-10 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0008_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='page_title',
            new_name='page_name',
        ),
    ]
